# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb29d827b4087486e111ae1fd0bc858ec42b241619cb968c906957fc66736c535d418cf7729c2d5c20fcd891e9fc4422b4ea41f99d4dae171426411a9d901e0

test:
  secret_key_base: b4d4f387968f44759525f8c9205f82f34110f87ddab9efabf5fcb74de5e66979df06bbfb5800d3582fad2affe347c6b76d103053a46cd7c5c211915efa835ce5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
